name: PR_unit_tests

on:
  pull_request:
    branches:
      - 'main'

jobs:
  Unit-test:
    name: Run unit tests on PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grants Permissions for Gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test